CREATE TABLE email_otp_challenges (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id    UUID         NOT NULL UNIQUE,
    user_id         BIGINT       NOT NULL,
    code_hash       VARCHAR(100) NOT NULL,
    purpose         VARCHAR(24)  NOT NULL,
    failed_attempts INTEGER      NOT NULL DEFAULT 0,
    expires_at      TIMESTAMP    NOT NULL,
    used_at         TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_sent_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_email_otp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_email_otp_user_purpose ON email_otp_challenges(user_id, purpose);
