package com.taskhub.enums;

public enum NotificationType {
    TASK_ASSIGNED,
    TASK_APPLICATION_RECEIVED,
    TASK_APPLICATION_ACCEPTED,
    TASK_APPLICATION_REJECTED,
    TASK_SUBMITTED,
    TASK_REVISION_REQUESTED,
    TASK_APPROVED,
    TASK_COMPLETED,
    TASK_DISPUTE_OPENED,
    TASK_DISPUTE_RESOLVED,
    TASK_MESSAGE_RECEIVED,
    TASK_STATUS_CHANGED,
    ESCROW_FUNDED,
    ESCROW_RELEASED,
    ESCROW_REFUNDED,
    PAYMENT_RECEIVED,
    PAYMENT_SENT,
    SYSTEM_ANNOUNCEMENT,
    REVIEW_RECEIVED,
    TASK_REMOVAL_REQUESTED,
    TASK_REMOVAL_APPROVED,
    TASK_REMOVAL_REJECTED
}
